"""Cheap quality scoring and routing for sparse retrieval frames.

Scores never redefine the source timeline. A failed frame can be excluded from
the expensive embedding lane while remaining available to coverage repair and
future dense temporal alignment.
"""

import cv2
import numpy as np


def resize_long_edge(img: np.ndarray, long_edge: int) -> np.ndarray:
    h, w = img.shape[:2]
    scale = long_edge / max(h, w)
    if scale >= 1.0:
        return img
    return cv2.resize(img, (round(w * scale), round(h * scale)), interpolation=cv2.INTER_AREA)


def quality_scores(rgb: np.ndarray) -> dict:
    gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
    brightness = float(gray.mean())
    contrast = float(gray.std())
    histogram = cv2.calcHist([gray], [0], None, [256], [0, 256]).ravel()
    probabilities = histogram[histogram > 0] / gray.size
    entropy = float(-(probabilities * np.log2(probabilities)).sum())
    return {
        "brightness_score": brightness,
        "blur_score": float(cv2.Laplacian(gray, cv2.CV_64F).var()),
        "contrast_score": contrast,
        "entropy_score": entropy,
        # Compatibility aliases for reports generated by the first pipeline.
        "brightness": brightness,
        "std_score": contrast,
    }


def passes(scores: dict, cfg) -> tuple[bool, str]:
    """Returns (ok, drop_reason)."""
    if not (cfg.brightness_min <= scores["brightness"] <= cfg.brightness_max):
        return False, "brightness"
    if scores["std_score"] < cfg.std_min:
        return False, "low_info"
    if scores["blur_score"] < cfg.blur_min:
        return False, "blur"
    return True, ""


def quality_route(scores: dict, cfg) -> tuple[bool, str, str]:
    """Return ``(quality_ok, reason, route)`` without deleting the frame."""
    ok, reason = passes(scores, cfg)
    return (True, "", "retrieval_embedding") if ok else (False, reason, "temporal_only")
